### ISSUE TITLE
[BUG] WEST is blacklisted as price asset

### ISSUE THREAD

**Issue by br0x** [wavesplatform/dex#110]
Order book request for pair LIQUID/WEST
https://matcher.wavesplatform.com/matcher/orderbook/7FzrHF1pueRFrPEupz6oiVGTUZqe8epvC7ggWUx8n1bd/4LHHvYGNKJUg5hj65aGD5vgScvCBmLpdRFtjokvCjSL8
returns:
```
{
    "result": null,
    "template": "The price asset {{assetId}} is blacklisted",
    "success": false,
    "error": 11538437,
    "message": "The price asset 4LHHvYGNKJUg5hj65aGD5vgScvCBmLpdRFtjokvCjSL8 is blacklisted",
    "params": {
        "assetId": "4LHHvYGNKJUg5hj65aGD5vgScvCBmLpdRFtjokvCjSL8"
    },
    "status": "InfoNotFound"
}
```

**Comment by vsuharnikov** [comment]
**wavesplatform/dex** is an open source project. We provide functionality, but any exchange may configure as it wishes.

Try to ask in concrete exchange support ;-)
