### ISSUE TITLE
Not getting response from matcher Api?

### ISSUE THREAD

**Issue by osiz-blockchainapp** [wavesplatform/dex#165]
Hi,
For creating own matcher i use waves-testnet_1.0.2_all.deb file 
Os : ubuntu 16

Config File :

`# Waves node settins
waves {
 blockchain.type = TESTNET
  # P2P Network settings
  network {
    # Network address
    bind-address = "0.0.0.0"

    # Port number
    port = 6863

    # Node name to send during handshake. Comment this string out to set random node name.
    node-name = "MyTESTNETnode123"

    # String with IP address and port to send as external address during handshake. Could be set automatically if uPnP is enabled.
    #declared-address = "1.2.3.4:6863"

    black-list-residence-time = 30 minutes
  }

  # Wallet settings
  wallet {
    # Password to protect wallet file
    password = "1234567890"

    # Wallet seed as BASE58 string
    seed = XXXXXXXXXXXXXXXXXXXXXXXXXX
  }

  # Blockchain settings
  blockchain.type = TESTNET

  # Node's REST API settings
  rest-api {
    # Enable/disable node's REST API
    enable = yes

    # Network address to bind to
    bind-address = "0.0.0.0"

    # Port to listen to REST API requests
    port = 6869

    # Hash of API key string
    api-key-hash = "H6nsiifwYKYEx6YzYD7woP1XCn72RVvx6tC1zjjLXqsu"
  }
	  waves.extensions = [
    "com.wavesplatform.dex.Matcher"
    # ... here may be other extensions
  ]
 
  waves.dex {
    account = "3PMyQhACo9YFLXBrxFt74EEqS3ELQoM6H4k" # This account must be known at the Node, e.g. created through POST /addresses
    bind-address = "0.0.0.0" # uncomment this line to accept connections from any host
  }

  # Matcher settings
  matcher {
    # Enable/disable matcher
    enable = yes

    # Matcher's account address
    account = "3PMyQhACo9YFLXBrxFt74EEqS3ELQoM6H4k"

    # Matcher REST API bind address
    bind-address = "0.0.0.0"

    # Matcher REST API port
    port = 6886

    # Minimum allowed order fee
    min-order-fee = 300000

    # Fee of order match transaction
    order-match-tx-fee = 300000

    # Matcher's directories
    matcher-directory = ${waves.directory}"/matcher"
    data-directory = ${waves.matcher.matcher-directory}"/data"
    journal-directory = ${waves.matcher.matcher-directory}"/journal"
    snapshots-directory = ${waves.matcher.matcher-directory}"/snapshots"

    # LevelDB's internal cache size
    leveldb-cache-size = 256M

    # Snapshots creation interval
    snapshots-interval = 1d

    # Invalid/Expired orders cleanup interval
    order-cleanup-interval = 5m

    # Maximum allowed amount of open orders
    max-open-orders = 1000

    # Maximum allowed amount of orders retrieved via REST
    rest-order-limit = 100

    # Maximum orders stored in OrderHistory per address
    max-orders-per-address = 1000

    # Base assets used as price assets
    price-assets = [
     "WAVES",
     "Fmg13HEHJHuZYbtJq8Da8wifJENq8uBxDuWoP9pVe2Qe",
     "HyFJ3rrq5m7FxdkWtQXkZrDat1F7LjVVGfpSkUuEXQHj",
     "2xnE3EdpqXtFgCP156qt1AbyjpqdZ5jGjWo3CwTawcux",
     "6pmDivReTLikwYqQtJTv6dTcE59knriaodB3AK8T9cF8"
   ]

    # Predefined ordering of base assets
    predefined-pairs = [
     {amountAsset = "WAVES", priceAsset = "Fmg13HEHJHuZYbtJq8Da8wifJENq8uBxDuWoP9pVe2Qe"},
     {amountAsset = "WAVES", priceAsset = "HyFJ3rrq5m7FxdkWtQXkZrDat1F7LjVVGfpSkUuEXQHj"},
     {amountAsset = "WAVES", priceAsset = "2xnE3EdpqXtFgCP156qt1AbyjpqdZ5jGjWo3CwTawcux"},
     {amountAsset = "WAVES", priceAsset = "6pmDivReTLikwYqQtJTv6dTcE59knriaodB3AK8T9cF8"},
     {amountAsset = "Fmg13HEHJHuZYbtJq8Da8wifJENq8uBxDuWoP9pVe2Qe", priceAsset = "2aSqCbvCTgvCpwkGsk4mea4tCLG4Zgp69aQDhHNvRUZv"},
     {amountAsset = "Fmg13HEHJHuZYbtJq8Da8wifJENq8uBxDuWoP9pVe2Qe", priceAsset = "8zEZuJcKPQmFuYgVe5ZMpxgiPLu5zBhjA6xgdGomQDaP"},
     {amountAsset = "Fmg13HEHJHuZYbtJq8Da8wifJENq8uBxDuWoP9pVe2Qe", priceAsset = "D2MNuUyA38pSKoV7F7vpS15Uhw9nw5qfbrGUfCLRNuRo"},
     {amountAsset = "2xnE3EdpqXtFgCP156qt1AbyjpqdZ5jGjWo3CwTawcux", priceAsset = "HyFJ3rrq5m7FxdkWtQXkZrDat1F7LjVVGfpSkUuEXQHj"}
   ]

    # Maximum difference with Matcher server time
    max-timestamp-diff = 3h

    # Blacklisted assets id
    blacklisted-assets: []

    # Blacklisted assets name
    blacklisted-names: []

    # Blacklisted addresses
    blacklisted-addresses: []
  }

}

include "local.conf"`

But am not getting any response from matcher api. Is that my config file is correct. 
Please a give a possible solution for that.
Thanks

**Comment by vsuharnikov** [comment]
@osiz-blockchainapp 
> Error: The WAVES-DWgwcZTMhSvnyYCoWLRUXXSH1RSkzThXLJhww9gwkqdn asset pair should be reversed

The right order in the config is:
```
price-assets = [
  DWgwcZTMhSvnyYCoWLRUXXSH1RSkzThXLJhww9gwkqdn,
  WAVES
]
```

See explanation in https://docs.waves.exchange/en/waves-matcher/matcher-api#asset-pair  ;)

**Comment by osiz-blockchainapp** [comment]
Hi, 
I configure waves full node in AWS.  The node synchronization was stopped on this block 1964603 then again restarted the waves node service then the node was not started to synchronized but it throws below error.
Error:
`WARN c.w.s.a.ExtensionAppender$ - Can't process fork starting with 4B5eZheiVAxMfpkwPgLKYzTe5j9LHyAet4jLWFwgkVjAGGsTgqBz6Nf2z1VJqusQqonKQPmeX86VyJTcMuGqXkQq, error appending block Block(FMi3E8S8tfzgsp2zUUA15pBbFCAKxXfT2WA7sjw1a6TM21wz8hgWDyE6MkLntFCv4pkdBy7CGnzS67WwW5CsjFn -> 4B5eZhe..., txs=75, features=Set(), rewardVote=600000000): GenericError(Block Block(FMi3E8S8tfzgsp2zUUA15pBbFCAKxXfT2WA7sjw1a6TM21wz8hgWDyE6MkLntFCv4pkdBy7CGnzS67WwW5CsjFn -> 4B5eZhe..., txs=75, features=Set(), rewardVote=600000000) is invalid: Block time 1583754581413 less than expected)`

Then i was upgraded waves node to this version (waves_1.1.10_all.deb) then again restarted waves node service but again getting the same error.
I take back up of node configuration file then removed all the old data of waves node after that i started node synchronization from scratch but still am receiving same error can you please help me to solve this issue. here attached screen short.
![Screenshot 2020 05 19 at 5 50 53 PM png PNG Image 1440%A0×%A0550 pixels ](https://user-images.githubusercontent.com/48212011/82337123-0788a400-9a09-11ea-9a70-16094944f04b.png)

**Comment by vsuharnikov** [comment]
Here the repository of Waves Node: https://github.com/wavesplatform/Waves
