### ISSUE TITLE
How to get the MATCHER Fee ? 

### ISSUE THREAD

**Issue by narmathamuthu** [wavesplatform/dex#166]
Hi Team , 

How to manage the my "MATCHER Accounts" ? 

Then how to get or view the my Matcher Fees ?

I got matcher address ( public key ) using given link.

Link : https://matcher.testnet.wavesnodes.com/api-docs/index.html#!/matcher/getMatcherPublicKey

But i don't know where to manage my matcher account details , my matcher balance ( Fees ) and other matcher settings. 

So please any one guide to me. 

Late 3 days i am struggling on matcher section.

**Comment by vsuharnikov** [comment]
Seems all issues solved. Thanks @username1565 ! :)
