### ISSUE TITLE
Waves Dex  Is it possible to create own matcher against the orders in alreay existing matcher? 

### ISSUE THREAD

**Issue by sultana-mnw** [wavesplatform/dex#167]
Hi Waves Team,

I want to create own dex like dex ethereum. I explore the documentation then i create buy and sell order using wavekeeper. 
Here i want to provide and maintain the Dex platform in waves but the problem is orders Fees is transferring to matcher keys. How could i controlled that and how can i create my own matcher key. please a give a possible solution for creating own Dex in waves platform.

Thanks.

**Comment by vsuharnikov** [comment]
> Another one doubt the sell/buy order fees 0.003 WAVES can be reduce after each successful transaction from buyer/seller is that is default or we can modify that.

Here some options: https://github.com/wavesplatform/dex/blob/master/dex/src/main/resources/application.conf#L92
