### ISSUE TITLE
I got java.lang.ClassNotFoundException trying to run this package.

### ISSUE THREAD

**Issue by hbastidas** [wavesplatform/dex#23]
hello i would like to learn waves and i want to run a matcher node to develop things about it, i'm testing such as documentation but i can't find a way to make it work

This is what I've been doing and the mistake I'm finding.

`IMACs-iMac:waves-dex hbastidas$ Java --add-modules=java.xml.bind -cp "/Users/hbastidas/projects/waves-dex/dex/target/dex-1.0.0-5-g0519aaa.jar:/Users/hbastidas/projects/waves-dex/dex/target/universal/dex-1.0.0-5-g0519aaa/lib/*" com.wavesplatform.Application`

```
Error: the main class com.wavesplatform.Application was not found or loaded
Caused by: java.lang.ClassNotFoundException: com.wavesplatform.Application
```
![Captura de Pantalla 2019-07-23 a la(s) 3 56 58 p  m](https://user-images.githubusercontent.com/298644/61743110-9170cd80-ad62-11e9-8e95-f31b4527d735.png)

How do I run this?

**Comment by vsuharnikov** [comment]
Hi! The DEX currently is an extension of NODE. According to README.md https://github.com/wavesplatform/dex#tgz you need Waves NODE's jar . So, the right command will be:
```
java --add-modules=java.xml.bind -cp "/absolute_path_to_fat_jar/waves-all.jar:/Users/hbastidas/projects/waves-dex/dex/target/dex-1.0.0-5-g0519aaa.jar:/Users/hbastidas/projects/waves-dex/dex/target/universal/dex-1.0.0-5-g0519aaa/lib/*" com.wavesplatform.Application
```
Note, the "/absolute_path_to_fat_jar/waves-all.jar" is required here

**Comment by hbastidas** [comment]
I'm sorry I made a mistake. I thought you were totally independent. Thank you.

**Comment by cryptoneobancoin** [comment]
thanks! @vsuharnikov

**Comment by vsuharnikov** [comment]
> I'm sorry I made a mistake. I thought you were totally independent. Thank you.
We are working on it this moment :) Hope, we will be independent soon
