### ISSUE TITLE
[SOLVED] Is there any JAR-file for extensions?

### ISSUE THREAD

**Issue by username1565** [wavesplatform/dex#37]
Is this matcher and grpc extension for nodes v1.0.0, v1.0.1. v1.0.2??

Is there any JAR-file? Why this not working on new versions of nodes?

**Comment by vsuharnikov** [comment]
> Is this matcher and grpc extension for nodes v1.0.0, v1.0.1. v1.0.2??
That's true for matcher.

Which gRPC extension? 
* If you meant `grpc-server`, it should. Please refer to https://github.com/wavesplatform/Waves/issues for more information about `grpc-server`.
* We have own gRPC extension, it is still in development

> Is there any JAR-file?
There ara DEB and TGZ artifacts. More information here: https://github.com/wavesplatform/dex#6-installing-and-running

**Comment by username1565** [comment]
Hello. I see matcher is working for node v0.17.1 with default config,
and I see here: https://github.com/wavesplatform/Waves/releases/tag/v1.0.0
for node v.1.0.0 matcher was been disabled, and not working with default config:
`Matcher and gRPC server have been refactored into an extension, and there's definitely more to come.`
So, by this reason, I found your extensions and asked about `matcher` and `grpc-server`...

After unpack, using 7z, `.tgz` -> into `.tar`, and `.tar` -> into `folder`, I see `jar-files` there, in the `/lib`-folder.
But... I still cann't run the Matcher REST API for node v1.0.2...
After unpack files, according [this guide](https://github.com/wavesplatform/dex#6-installing-and-running) I created `.bat`-file, with name `import_extensions.bat`, and with content:
```
G:
cd "G:\coins\WAVES_FULL_NODE\NEW_NODE"
java -cp "G:\coins\WAVES_FULL_NODE\NEW_NODE\waves-all-1.0.2.jar;G:\coins\WAVES_FULL_NODE\NEW_NODE\dex-1.0.1\dex-1.0.1\lib\*" com.wavesplatform.Application node.conf
pause
```

in `node.conf`, I did write the following strings:
```
# ... here many lines of your Node's configuration
 
waves.extensions = [
  "com.wavesplatform.dex.Matcher"
  # ... here may be other extensions
]
 
waves.dex {
  account = "MY NODE WAVES ADDRESS" # This account must be known at the Node, e.g. created through POST /addresses
  # bind-address = "0.0.0.0" # uncomment this line to accept connections from any host
}
```
Also, in `node.conf` I have mather configuration earlier:
```
# Matcher settings
  matcher {
    # Enable/disable matcher
    enable = yes

    # Matcher's account address
    account = "WAVES_ADDRESS_OF_MY_NODE"

    # Matcher REST API bind address
    bind-address = "0.0.0.0"
    bind-address = "[::]"
    bind-address = "127.0.0.1"

    # Matcher REST API port
    port = 6886

    # Minimum allowed order fee
    min-order-fee = 300000

    # Fee of order match transaction
    order-match-tx-fee = 300000

    # Matcher's directories
    matcher-directory = ${waves.directory}"/matcher"
    data-directory = ${waves.matcher.matcher-directory}"/data"
    journal-directory = ${waves.matcher.matcher-directory}"/journal"
    snapshots-directory = ${waves.matcher.matcher-directory}"/snapshots"

    # LevelDB's internal cache size
    leveldb-cache-size = ${waves.leveldb-cache-size}

    # Snapshots creation interval
    snapshots-interval = 1d

    # Invalid/Expired orders cleanup interval
    order-cleanup-interval = 5m

    # Maximum allowed amount of open orders
    max-open-orders = 1000

    # Maximum allowed amount of orders retrieved via REST
    rest-order-limit = 100

    # Maximum orders stored in OrderHistory per address
    max-orders-per-address = 1000

    # Base assets used as price assets
    price-assets: []

    # Predefined ordering of base assets
    predefined-pairs: []

    # Maximum difference with Matcher server time
    max-timestamp-diff = 3h

    # Blacklisted assets id
    blacklisted-assets: []

    # Blacklisted assets name
    blacklisted-names: []

    # Blacklisted addresses
    blacklisted-addresses: []
  }
```
But... After running `import_extensions.bat`, [I don't see](https://github.com/wavesplatform/Waves/issues/2523) the working [Matcher REST API](https://matcher.wavesplatform.com/api-docs/index.html) at port 6886 on my localhost...
Only [Node REST API](https://nodes.wavesplatform.com/api-docs/index.html) available at port 6869.
And only in version of node v0.17.1, Matcher REST API available at port 6886, with my previous settings.

So, how to configure and run Matcher REST API, using your extensions, for nodes v1.0.0, v1.0.1, v1.0.2???
Is there any guides??

**Comment by koloale** [comment]
Hi @username1565! v1.0.1.12 it's just the version built from 1.0.1 version containing the internal configuration to run on our internal servers, like setups for Kafka and nodes pool. So it is the latest version currently.
